### ISSUE TITLE
List Status code by type

### ISSUE THREAD

**Issue by akabiru** [akabiru/hscode#16]
Add functionality to list status code by type. E.g.

    $ hscode -l 2xx

This should generate the following. Note the title.
```
2xx Success

200 - OK
201 - Created
202 - Accepted
203 - Non-authoritative Information
204 - No Content
205 - Reset Content
206 - Partial Content
207 - Multi-Status
208 - Already Reported
226 - IM Used
```

Reference:
```
1xx Informational
2xx Sucess
3xx Redirection
4xx Client Error
5xx Server Error
```

**Comment by andela-ydaniju** [comment]
I think I can play around with this.

**Comment by akabiru** [comment]
@andela-ydaniju Awesome! 🙌🏾  Be sure to raise a WIP PR soon as you can with a `work-in-progress` tag just to keep track of things.
