### ISSUE TITLE
LoadError when I try to use hscode

### ISSUE THREAD

**Issue by Bopchy** [akabiru/hscode#19]
<img width="1095" alt="screen shot 2016-11-23 at 2 39 11 pm" src="https://cloud.githubusercontent.com/assets/12303856/20591015/736f5e92-b237-11e6-8087-e985c70440d6.png">

After going through the process of the installation script, I still receive a LoadError. This is fixed by `gem install bundler` though

**Comment by akabiru** [comment]
Thanks for raising this @Bopchy. Looking into patching this issue in the next release.

**Comment by akabiru** [comment]
Thanks @Habu-Kagumba We should look into this.

**Comment by andela-ydaniju** [comment]
The issue is on line 3 of `bin/hscode`. Bundler is expected to be installed, else `hscode` will throw an error. There are 3 options here:

1. Add Bundler as a dependency in the gemspec.
2. Update documentation that user needs to have bundler installed to make `hscode` work properly.

**Comment by Habu-Kagumba** [comment]
Thanks @andela-ydaniju went with door number 3.

**Comment by andela-ydaniju** [comment]
I see you reopened the issue @Habu-Kagumba. Did it work?

**Comment by akabiru** [comment]
It worked @andela-ydaniju. Thanks for your input.

**Comment by andela-ydaniju** [comment]
No problem.
