### ISSUE TITLE
yarn/npm install

### ISSUE THREAD

**Issue by bomb1e** [akabiru/hscode#20]
add installation via yarn or npm

**Comment by Habu-Kagumba** [comment]
Hmmm... not sure I understand your issue. The tool is built with **Ruby** hence the need to install it as a **gem**.
**npm** and **yarn** are **JavaScript** package managers.

**Comment by bomb1e** [comment]
Oh yeah, missed that

**Comment by akabiru** [comment]
@bomb1e to add onto what @Habu-Kagumba said, we understand `gem` is not the easiest to use if you don't have a ruby environment setup. In this regard, we have an issue open https://github.com/akabiru/hscode/issues/11 meant to address this sort of problem.
